import React from 'react';
import { techLogos } from '../data/techLogos';

interface TechLogoProps {
  name: string;
  className?: string;
}

/**
 * One self-hosted logo per skill name, or nothing.
 *
 * This used to hotlink ~80 SVGs and favicons from cdn.jsdelivr, worldvectorlogo and
 * vendor /favicon.ico URLs. Four of those set Cloudflare cookies, several were
 * CORP-blocked or 404, and one favicon was 210 KB — together the entire Lighthouse
 * best-practices gap and ~80 requests on the home page. The assets now live in
 * public/images/logos/tech (generated by scripts/fetch-tech-logos.js) and the map is
 * src/data/techLogos.ts. The skill name is always rendered beside the icon by
 * Skills.tsx, so a name without an icon simply has no icon.
 */
const TechLogo: React.FC<TechLogoProps> = ({ name, className = 'w-8 h-8' }) => {
  const src = techLogos[name];
  if (!src) return null;
  return (
    <img
      src={src}
      alt=""
      aria-hidden="true"
      width={16}
      height={16}
      loading="lazy"
      decoding="async"
      className={`${className} object-contain`}
    />
  );
};

export default TechLogo;
